export const NAMES = [
  'Learning Style Preference',
  'Post-Event Survey',
  'Marketing Request Form',
  'Conservation Park Finder',
  'hercules mulligan net!!',
  'Orbital Digital',
  'Customer Feedback',
  'Website Questionnaire',
  'Billpay',
  'CRF',
  'Example Customer Experience Survey (copy)',
  'Debra VanderWeit',
  'Graphic Battle Updates',
  'Winter Symposium',
  'The Senses',
  'Contact Form From Scratch',
  'Customer Satisfaction Survey',
  'PROJECT MOTION PASTORAL CARE',
  'Questionnaire de recrutement 1',
  'FLD Email Feature Request',
  'Ask Amber Submissions',
  'new',
  'Try PRO',
  'louise-and-clark-order-form',
  'Database Alumni',
  'Investor',
  'Actualization process feedback',
  'Registration Form',
  'Customer Satisfaction Survey',
  'SES Professionals',
  'SE Asia',
  'Centerpieces & Reception Lesson 4 feedback',
  'Gulfood 2016 Survey',
  'Photography Session Agreement and Questionnaire',
  'Busenitz Family New',
  'Melissa',
  'TestWP',
  'Mentee Survey',
  'monochrome network',
  'Membership Application',
  'Trivia Quiz',
  'Content & Cocktails: Spotlight on Retail',
  'Flicks.co.nz: Pick the Oscars (copy)',
  'Encompass Worship Team Application Form 2016',
  'my',
  'Post Test (copy)',
  'Luigify answers',
  'Demographic Survey Questions',
  'Contact Form (copy)',
  'Market Research Survey',
  'Contact Us',
  'Bubble Pop Designer',
  'Branding Questionnaire',
  'ads',
  'Job Application Form',
  'Trump Builder',
  'Goodman Crafts Consignment Ring Order Form',
  'Straw Poll',
  'the FRONT',
  'Post Event Survey',
  'RUNNER - Harmony Northway - 30 Day Review',
  'Product Placement',
  'Market Research Survey',
  'Test',
  'New Listing (copy)',
  'Investor',
  'School Teachers Survey',
  'Contact Form',
  'New Listing',
  'fabian',
  'Teacher Evaluation Form',
  'Jellofeva',
  'Instagram Shout Request',
  'Contact Form',
  'Quiz Template',
  'Contact Form',
  'Survey - FB Page',
  'Personal',
  'Fuck Off',
  'Do you have a project?',
  'USA',
  'Satisfaction Survey',
  'Future-You vs. Present-You',
  'Marketing Survey (copy)',
  'Project Promotion',
  'THESIS',
  'Membership Application',
  'School Parents Survey',
  'Groupchat',
  'Oscars Poll',
  'teste 1',
  'Mi formulario',
  'teste 1',
  'ThatCrazyTaco',
  'Style Questionnaire',
  'unward and upward sam&colby',
  'Trump Builder',
  '#projectprrrrr',
  'Believer Subscriber prototype',
  'Space Ghost_Survey February 9, 2016',
  'Distribution Inquiry',
  'Try PRO',
  'Quality February 9, 2016',
  'February 9, 2016',
  'One Foot Out The Door',
  'Starch Club',
  'Justice League_Survey February 9, 2016',
  'Inception_Survey February 9, 2016',
  'Hero Turtles_Survey February 9, 2016',
  'Galactica_Survey February 9, 2016',
  'OHSS Scope Survey',
  'Heisenberg_Survey 9, 2016',
  'Galactica_Survey 9, 2016 (copy)',
  'Drop Off/Delivery (copy)',
  'Ready For Love Session Sign Up (copy)',
  'Cerberus_Survey February 9, 2016',
  'Caprica_Survey February 9, 2016',
  'Event Registration',
  'Pass On',
  'Alias_Survey February 9, 2016',
  '2016 Safety Program Eval',
  'Caprica_Survey February 9, 2016 (copy) (copy)',
  'Alias_Survey February 9, 2016 (copy)',
  'Post Test',
  'Full-Access Account Shop',
  'Winter 2016 Midway Survey PT - Front End',
  'For student ambassadors interested in C.A.',
  'Encuesta de Satisfacción HOST FAMILY',
  'bangtan',
  'Post-Event Survey',
  'Winter 2016 Midway Survey PT - Section 3',
  'Branding Questionnaire',
  'ENZASA',
  // 'FMS Monterey Winter 2016 Overall Program Evaluation',
  'Linea Etica',
  'Front Facing Camera',
  // 'SGH',
  // 'Branding Questionnaire',
  // 'Winter 2016 Midway Survey PT - Section 2',
  // 'Customer Satisfaction Survey',
  // '360 Degree Feedback',
  // 'Winter 2016 Midway Survey PT - Section 1',
  'Try PRO',
  // 'Evaluación de Asociado',
  'test',
  // 'Market Research Survey',
  // 'Donation Form',
  // 'QBR Feedback - Q1 2016 (pt 1)',
  // 'Test',
  // 'ielts',
  // 'ePatient Application - Research & Precision Medicine',
  // 'Donation Form',
  // 'Test (copy)',
  // 'TCF Fall/Winter 2015 Mid Point Check-in',
  // 'test',
  // 'noelles 2k celebration',
  // 'Registration Form',
  // 'Induction Quiz',
  // 'Customer Satisfaction Survey',
  // 'ePatient Application - Entrepreneurship',
  // 'EMPRENDUM',
  // 'Student Satisfaction Survey',
  // 'Courier sign up form',
  // 'YC Assembly',
  // 'Slack Community Signup Form (copy)',
  // 'barbs form',
  // 'testing',
  // 'Registration Form',
  // 'Universities',
  // 'Slack Community Signup Form (copy)',
  // 'YEAR 13 AWARDS',
  // 'Innervate Customer Onboard',
  // 'CU-CPC: Set Name (copy)',
  // 'Test',
  // 'McCall & Almy Logo Discovery',
  // 'Market Research Survey',
  // 'Skills (copy)',
  // 'M7 Capstone (Camilo)',
  // 'M7 Capstone (Aaron)',
  // 'What do you struggle with the most when it comes to being creative?',
  // 'M7 Capstone (Allison)',
  // 'Sign Up Sheet',
  // 'Contact Form',
  // 'School Survey',
  // 'Try PRO',
  // 'Winter 2016 Midway Survey PT - Section 1',
  // 'IG Shoutout',
  // 'Trial $99/mo Sponsored Welcome Emails: Master Advertiser Agreement',
  // 'Auto kaufen (copy)',
  // 'Answerbox Slack Interactions',
  // 'ANDRESSA',
  // 'About Our Kids',
  // 'willie',
  // 'Contact Form',
  // 'samanthq',
  // 'SD Met Pre & Post',
  // 'Order Type',
  // 'mostafa',
  // 'Post-Event Survey',
  // 'Определение предочтений',
  // 'NURUL WAHYUANDINI',
  // 'resource requests 2016',
  // 'Trump Builder',
  // 'Interview',
  // 'Customer Satisfaction Survey',
  // 'Scrub Survey Feb 2016',
  // 'Spanish TpT',
  // 'Trump Builder',
  // 'Trump Builder',
  // 'Wow Jewelry',
  // 'Speaker Nomination',
  // 'Inquiry',
  // 'Social Media Survey (copy)',
  // 'Gut Check',
  // 'Medtraq Doctor Survey',
  // 'Registration Form (copy)',
  // 'DisruptHR Sydney - Pre event survey (copy)',
  // 'CU Survey',
  // 'info',
  // 'UBREW CREW FOUNDER weekly comms',
  'Volunteer Application Form',
  'Registration Form',
  'Trump Builder',
  // 'Superclass Tutors',
  // 'Full-Access Account Shop',
  // 'Full-Access Account Shop',
  // 'Full-Access Account Shop',
  // 'iGPFun F.Renault 2016 S2',
  // 'Luisa Mesa',
  // '1099Online.com - Post 2015 Survey',
  // 'Entrevista de Salida KraftHeinz',
  // 'test',
  // 'Beta Invite Registration (copy)',
  // 'Everlane Fit Sessions – Shirts 2016 Scheduling',
  // 'Event Registration',
  // 'Registration Form',
  // 'Membership Application',
  // 'Demographic Survey',
  // 'Post-Event Survey',
  // 'Slack Community Signup Form',
  // 'Jopwell - Medium Onboarding Survey (copy)',
  // 'Which ERP Quiz',
  'Marketing Survey',
  // 'FSOI 2016',
  'Plantilla Si Navega',
  // 'Community Support Ranking',
  // 'NYEVENTS.club',
  // 'LauraS',
  // 'Demographic Survey',
  // 'MOV YFH Programming Event Speakers/Partners Form (copy)',
  // 'FORMATO DE APLICACIÓN PARA CONVOCATORIA TIMEBAG',
  // 'RMU Roommate Portal',
  // 'Branding Questionnaire',
  // 'RMU Roommate Portal (copy) (copy)',
  // 'Drop Off/Delivery',
  // 'Test',
  // 'On Lok Central Survey',
  // 'My First Form',
  // 'Registration Form (copy)',
  // 'Try PRO',
  // 'Enduroboost Adaptogens Dosage Guide',
  // 'Registration Form',
  // '2016 Bio Narrative',
  // 'Lesson Report',
  // 'Net Promoter Score® Template',
  // 'ana',
  // 'Aflah Z',
  // 'Tester123',
  // 'Nlfdjs',
  // 'Contact Form (copy)',
  // 'Demographic Survey',
  // 'Branding Questionnaire',
  // 'BBB Internal Survey',
  // 'Registration Form',
  // 'RMHC Peds Survey',
  // 'ABLE',
  // 'School Survey',
  // 'gatos y perros (copy)',
  // 'Yoga Instructor Market Research Survey',
  // 'Robert Soinski',
  // 'Customer Satisfaction Survey',
  // 'Lead Generation',
  // 'raul rodriguez',
  // 'Try PRO',
  // 'Contact Form (copy)',
  // 'Hackpoly 2016 Post-Event Survey',
  // 'Project Donut Form',
  // 'kim',
  // 'Pitch Contest Fein-Ibef',
  // 'EA Group Affiliation',
  // 'Contact Form',
  // 'prince nekpenekpen',
  // 'ПРЕТЕНЗИЯ',
  // 'If I Run',
  // 'Company job description',
  // 'Test',
  // 'Interested nonsubscribers',
  // 'Post-Event Survey',
  // 'Pregrado-ArqIX-Inic-Fin-A',
  // 'FCSS Student Bazaar Vendor Form',
  // 'Survey February 9, 2016',
  // 'ePatient Application - Design',
  // 'yara thabt (copy)',
  // 'Modashion*s Advisor To CEO Vote',
  // 'Registration Form',
  // 'uberPOOL Newsroom Series',
  // 'App Survey',
  // 'Pregrado-CSalud3-Inc-Fin-E',
  // 'Pregrado-CSalud3-Inc-Fin-D',
  // 'RMU Roommate Portal (copy)',
  // 'Employee Satisfaction Survey',
  // 'York Region Student Bazaar',
  // 'Pregrado-CSalud3-Inc-Fin-C',
  // 'Teste',
  // 'Sok a Joe Customer Survey',
  // 'Pregrado-CSalud3-Inc-Fin-B',
  // 'Market Research Survey',
  // 'Marketing Survey',
  // 'New Client Questionnaire',
  // 'Lawyer meetings reimbursement',
  // 'BAAAHS 2015 - The aftermath',
  // 'BAAAHS 2015 - The aftermath',
  'Anfrage Stephan Heinrich'
]
export const TAGS = [
  'blubber',
  'pencil',
  'cloud',
  'water',
  'computer',
  'school',
  'network',
  'hammer',
  'walking',
  'mediocre',
  'literature',
  'chair',
  'two',
  'window'
]
