export const NAMES = [
  'How was the math test?',
  'Cats are good pets, for they are clean and are not noisy.',
  'Writing a list of random sentences',
  'Malls are great places to shop; I can find everything I need under one roof.',
  'I want to buy a onesie… but know it won’t suit me.',
  'The old apple revels in its authority.',
  'He didn’t want to go to the dentist, yet he went anyway.',
  'She only paints with bold colors; she does not like pastels.',
  'Tom got a small piece of pie.',
  'I checked to make sure that he was still alive.',
  'The mysterious diary records the voice.',
  'I really want to go to work, but I am too sick to drive.',
  'Hurry!',
  'Italy is my favorite country',
  'I currently have 4 windows open up… and I don’t know why.',
  'I often see the time 11:11 or 12:34 on clocks.',
  'The quick brown fox jumps over the lazy dog.',
  'They got there early, and they got really good seats.',
  'I will never be this young again. Ever. Oh damn… I just got older.',
  'Abstraction is often one floor above you.',
  'I want more detailed information.',
  'I think I will buy the red car, or I will lease the blue one.',
  'I am never at home on Sundays.',
  'Is it free?',
  'He turned in the research paper on Friday',
  'We have never been to Asia, nor have we visited Africa.',
  'A purple pig and a green donkey flew',
  'The river stole the gods.',
  'Christmas is coming.',
  'When I was little',
  'She works two jobs to make ends meet',
  'Should we start class now, or should we wait for everyone to get here?',
  'I am happy to take your donation; any amount will be greatly appreciated.',
  'The stranger officiates the meal.',
  'She always speaks to him in a loud voice.',
  'The waves were crashing on the shore; it was a lovely sight.',
  'Wow, does that work?',
  'If Purple People Eaters are real… where do they find purple people to eat?',
  'She advised him to come back at once.',
  'Rock music approaches at high velocity.',
  'Please wait outside of the house.',
  'He said he was not there yesterday; however, many people saw him there.',
  'There were white out conditions in the town',
  'I hear that Nancy is very pretty.',
  'He told us a very exciting adventure story.',
  'Last Friday in three week’s time',
  'She folded her handkerchief neatly.',
  'This is a Japanese doll.',
  'The lake is a long way from here.',
  'The body may perhaps compensates for the loss of a true metaphysics.',
  'This is the last random sentence I will be writing and I am going to stop mid-sent',
  'There was no ice cream in the freezer, nor did they have money to go to the store.',
  'We have a lot of rain in June.',
  'Everyone was busy, so I went to the movie alone.',
  'Lets all be unique together until we realise we are all the same.',
  'Two seats were vacant.',
  'We need to rent a room for our party.',
  'Joe made the sugar cookies; Susan decorated them.',
  'If you like tuna and tomato sauce- try combining the two',
  'The clock within this blog and the clock',
  'The shooter says goodbye to his love.',
  'Mary plays the piano.',
  'The memory we used to share is no longer coherent.',
  'Sixty-Four comes asking for bread.',
  'The book is in front of the table.',
  'Where do random thoughts come from?',
  'It was getting dark, and we weren’t there yet.',
  'Let me help you with your baggage.',
  'He ran out of money, so he had to stop playing poker.',
  'A glittering gem is not enough.',
  'She was too short to see over the fence.',
  'I love eating toasted cheese and tuna sandwiches.',
  'My Mum tries to be cool by saying that she likes all the same things that I do.',
  'Wednesday is hump day, but has anyone asked the camel if he’s happy about it?',
  'I would have gotten the promotion, but my attendance wasn’t good enough.',
  'She did not cheat on the test, for it was not the right thing to do.',
  'I am counting my calories, yet I really want dessert.',
  'She did her best to help him.',
  'The sky is clear; the stars are twinkling.',
  'A song can make or ruin a person’s day if they let it get to them.',
  'If I don’t like something, I’ll stay away from it.',
  'Check back tomorrow; I will see if the book has arrived.'
]
export const TAGS = [
  'blubber',
  'pencil',
  'cloud',
  'water',
  'computer',
  'school',
  'network',
  'hammer',
  'walking',
  'mediocre',
  'literature',
  'chair',
  'two',
  'window'
]
